export const CATEGORIES = {
  "Critical Care": [
    "ABG Interpretation",
    "Acid\u2013Base Disorders",
    "Airway Management",
    "Cardiac ICU",
    "Electrolyte Emergencies",
    "Hemodynamic Monitoring",
    "ICU Medications",
    "ICU Monitoring & Equipment",
    "Lines & Tubes",
    "Massive Transfusion",
    "Mechanical Ventilation",
    "Multi-Organ Failure",
    "Neurological ICU",
    "Nutrition in Critical Care (Enteral/TPN ICU)",
    "Renal ICU",
    "Respiratory Failure / ARDS",
    "Resuscitation / Code Blue",
    "Sedation & Paralytics",
    "Sepsis & Septic Shock",
    "Shock States",
    "Temperature Management",
    "Trauma & Emergency Care",
    "Withdrawal of Care / End-of-Life ICU"
  ],

  "Emergency Nursing": [
    "Airway Emergencies",
    "Anaphylaxis",
    "Bleeding / Hemorrhage",
    "Burns Emergency",
    "Cardiac Emergencies",
    "Cardioversion",
    "Chest tube",
    "Defibrillation",
    "Disaster Nursing",
    "Drowning",
    "Emergency Procedures",
    "Environmental Emergencies",
    "Head Injury / Spinal Injury",
    "Heat stroke",
    "Hypothermia",
    "Insect bites",
    "Intubation",
    "Mass Casualty Incidents",
    "Myocardial Infarction Emergency",
    "Obstetric Emergencies",
    "Overdose",
    "Pediatric Emergencies",
    "Poisoning",
    "Primary Survey (ABCDE)",
    "Rapid Response / Code Blue",
    "Respiratory Emergencies",
    "Seizures / Status Epilepticus",
    "Shock Emergency",
    "Snake bites",
    "Stroke Emergency",
    "Trauma",
    "Triage"
  ],

  "Fundamentals": [
    "Admission, Transfer & Discharge",
    "Assistive Devices",
    "Basic Care & Comfort",
    "Blood Transfusion",
    "Communication & Therapeutic Communication",
    "Cultural Considerations",
    "Delegation",
    "Documentation",
    "Elimination",
    "End-of-Life Care",
    "Enteral Feeding",
    "Ethical Issues",
    "Foley Catheter Care",
    "Hygiene",
    "Infection Control",
    "Intraoperative Care",
    "IV Therapy",
    "Isolation Precautions",
    "Legal Issues",
    "Medication Administration",
    "Mobility & Positioning",
    "Nutrition",
    "Ostomy Care",
    "Oxygen Therapy",
    "Pain Management",
    "Palliative Care Basics",
    "Parenteral Nutrition (TPN)",
    "Patient Education",
    "Perioperative Care",
    "Postoperative Care",
    "Preoperative Care",
    "Prioritization",
    "Restraints",
    "Safety & Fall Prevention",
    "Specimen Collection",
    "Sterile Technique",
    "Vital Signs",
    "Wound Care"
  ],

  "Pediatrics": [
    "Chronic Illness in Children",
    "Congenital Disorders",
    "Developmental Milestones",
    "Family-Centered Care",
    "Growth & Development",
    "Immunizations",
    "Pediatric Abuse & Neglect",
    "Pediatric Assessment",
    "Pediatric Cardiac",
    "Pediatric Emergencies",
    "Pediatric Endocrine",
    "Pediatric Fluid & Electrolytes",
    "Pediatric Gastrointestinal",
    "Pediatric Hematology",
    "Pediatric Infectious Diseases",
    "Pediatric Medication Administration",
    "Pediatric Neurological",
    "Pediatric Nutrition",
    "Pediatric Oncology",
    "Pediatric Pain Management",
    "Pediatric Procedures & Postoperative Care",
    "Pediatric Renal & Urinary",
    "Pediatric Respiratory",
    "Pediatric Safety & Injury Prevention",
    "Pediatric Vital Signs"
  ],

  "Pharmacology": [
    "Anti-Inflammatory Drugs",
    "Anticoagulants",
    "Antidepressants",
    "Antidotes",
    "Antifungals",
    "Antiplatelets",
    "Antiparasitic Drugs",
    "Antipsychotics",
    "Antiseizure Drugs",
    "Antituberculosis Drugs",
    "Antivirals",
    "Antibiotics",
    "Cardiovascular Drugs",
    "Drug Toxicity",
    "Emergency Drugs",
    "Electrolyte Replacement Medications",
    "Endocrine Drugs",
    "Gastrointestinal Drugs",
    "Hematologic Drugs",
    "Immunosuppressants",
    "Immunizations / Vaccines",
    "IV Therapy & Parenteral Medications",
    "Medication Administration & Safety",
    "Medication Calculations",
    "Mood Stabilizers",
    "Neurological Drugs",
    "Obstetric & Gynecologic Drugs",
    "Oncology Drugs (Chemotherapy)",
    "Pain Medications (Analgesics)",
    "Pediatric Drugs",
    "Psychiatric Drugs",
    "Respiratory Drugs",
    "Sedatives & Hypnotics",
    "Thrombolytics"
  ]
};

export const categoryList = Object.keys(CATEGORIES);
