// NCLEX Categories — 14 main categories with subcategories
// All subcategories arranged alphabetically within each category
// Categories arranged A-Z

export const CATEGORIES = {
  "Adult Health": [
    "Acid-Base Imbalances",
    "Acute Coronary Syndrome",
    "Acute Kidney Injury (AKI)",
    "Acute Respiratory Distress Syndrome (ARDS)",
    "Addison's Disease",
    "Anemia",
    "Aortic Aneurysm",
    "Asthma",
    "Burns",
    "Cancer (General Oncology)",
    "Cerebrovascular Accident (Stroke)",
    "Chronic Kidney Disease (CKD)",
    "Chronic Obstructive Pulmonary Disease (COPD)",
    "Cirrhosis",
    "Congestive Heart Failure (CHF)",
    "Coronary Artery Disease (CAD)",
    "Cushing's Syndrome",
    "Deep Vein Thrombosis (DVT)",
    "Dementia",
    "Diabetes Mellitus",
    "Diabetic Ketoacidosis (DKA)",
    "Dialysis",
    "Dysrhythmias",
    "Esophageal Varices",
    "Fluid Imbalance",
    "Fractures",
    "Guillain-Barre Syndrome",
    "Head Injury",
    "Heart Failure",
    "Hepatitis",
    "Hyperkalemia",
    "Hyperthyroidism",
    "Hypokalemia",
    "Hypothyroidism",
    "Liver Failure",
    "Myasthenia Gravis",
    "Myocardial Infarction (MI)",
    "Oxygen Therapy",
    "Pancreatitis",
    "Parkinson's Disease",
    "Peptic Ulcer Disease (PUD)",
    "Peripheral Arterial Disease (PAD)",
    "Pneumonia",
    "Pneumothorax",
    "Pulmonary Embolism (PE)",
    "Renal Failure",
    "Respiratory Failure",
    "Sepsis",
    "Shock",
    "Sickle Cell Disease",
    "Spinal Cord Injury",
    "Tracheostomy Care",
    "Tuberculosis (TB)",
    "Urinary Tract Infection (UTI)",
    "Wound Care"
  ],

  "Critical Care": [
    "Acute Coronary Syndrome",
    "Acute Kidney Injury",
    "Acute Respiratory Distress Syndrome (ARDS)",
    "Airway Management",
    "Arterial Blood Gas (ABG) Interpretation",
    "Arterial Lines",
    "Cardiac Arrest",
    "Cardiac Monitoring",
    "Cardiogenic Shock",
    "Central Venous Access",
    "Central Venous Pressure (CVP) Monitoring",
    "Defibrillation",
    "Endotracheal Intubation",
    "Hemodynamic Monitoring",
    "Hemorrhagic Shock",
    "Hypovolemic Shock",
    "Intra-Aortic Balloon Pump (IABP)",
    "Intracranial Pressure (ICP) Monitoring",
    "Mechanical Ventilation",
    "Multiple Organ Dysfunction Syndrome (MODS)",
    "Neurological Emergencies",
    "Non-Invasive Ventilation (BiPAP/CPAP)",
    "Post-Cardiac Arrest Care",
    "Pulmonary Artery Catheter",
    "Sedation Management",
    "Sepsis Management",
    "Septic Shock",
    "Shock Management",
    "Vasopressors",
    "Ventilator Weaning"
  ],

  "Dosage Calculations": [
    "Dimensional Analysis",
    "Drug Concentration Calculations",
    "Drug Reconstitution",
    "Flow Rate Calculations",
    "Heparin Drip Calculations",
    "Insulin Dose Calculations",
    "IV Bolus Calculations",
    "IV Infusion Calculations",
    "Loading Dose Calculations",
    "Maintenance Dose Calculations",
    "Milliequivalent (mEq) Calculations",
    "Pediatric Dosage Calculations",
    "Percentage and Ratio Calculations",
    "Unit Conversion",
    "Weight-Based Dosing"
  ],

  "EKG/Cardiac Monitoring": [
    "12-Lead ECG Interpretation",
    "Atrial Fibrillation",
    "Atrial Flutter",
    "AV Block (First Degree)",
    "AV Block (Second Degree - Type I)",
    "AV Block (Second Degree - Type II)",
    "AV Block (Third Degree)",
    "Heart Blocks",
    "Junctional Rhythms",
    "Myocardial Infarction Patterns",
    "Normal Sinus Rhythm",
    "PACs (Premature Atrial Contractions)",
    "PVCs (Premature Ventricular Contractions)",
    "ST Elevation (STEMI)",
    "Sinus Bradycardia",
    "Sinus Tachycardia",
    "Supraventricular Tachycardia (SVT)",
    "Torsades de Pointes",
    "Ventricular Fibrillation",
    "Ventricular Tachycardia"
  ],

  "Emergency Nursing": [
    "Abdominal Emergencies",
    "Allergic Reactions and Anaphylaxis",
    "Altered Mental Status",
    "Anaphylactic Shock",
    "Asthma Exacerbation",
    "Burn Emergencies",
    "Cardiac Arrest",
    "Cardiac Emergencies",
    "Carbon Monoxide Poisoning",
    "Chest Trauma",
    "Concussion",
    "Drug Overdose",
    "Fractures and Dislocations",
    "Head Trauma",
    "Heat Emergencies (Heat Stroke/Exhaustion)",
    "Hemorrhage Control",
    "Hypertensive Emergency",
    "Intubation and Airway Management",
    "Neurological Emergencies",
    "Obstetric Emergencies",
    "Penetrating Trauma",
    "Poisoning",
    "Psychiatric Emergencies",
    "Pulmonary Embolism",
    "Respiratory Emergencies",
    "Sepsis",
    "Spinal Cord Injury",
    "Stroke Assessment",
    "Triage",
    "Wound Management"
  ],

  "Fundamentals": [
    "Activity and Immobility",
    "Admission Assessment",
    "Asepsis and Infection Control",
    "Assessment Techniques",
    "Body Mechanics",
    "Bowel Elimination",
    "Communication",
    "Death and Dying",
    "Delegation to UAP",
    "Documentation",
    "Fall Prevention",
    "Foley Catheter Insertion",
    "Health Assessment",
    "Infection Control",
    "Informed Consent",
    "Injections (IM, SC, ID)",
    "Intravenous Fluid Therapy",
    "Isolation Precautions",
    "Maslow's Hierarchy of Needs",
    "Medication Administration",
    "Nurse-Patient Relationship",
    "Nutrition",
    "Oxygen Administration",
    "Pain Assessment",
    "Pain Management",
    "Patient Education",
    "Patient Identification",
    "Patient Rights",
    "Patient Safety Goals",
    "Personal Protective Equipment (PPE)",
    "Range of Motion Exercises",
    "Restraints",
    "Safety",
    "Specimen Collection",
    "Standard Precautions",
    "Surgical Asepsis",
    "Temperature Assessment",
    "Therapeutic Communication",
    "Vital Signs",
    "Wound Care"
  ],

  "Health Promotion & Maintenance": [
    "Aging Process",
    "Antepartum Care",
    "Cancer Screening",
    "Contraception",
    "Developmental Milestones",
    "Developmental Stages",
    "Diet and Exercise",
    "Disease Prevention",
    "Family Planning",
    "Growth Charts",
    "Health Promotion",
    "Immunization Schedules",
    "Immunizations",
    "Intrapartum Care",
    "Newborn Screening",
    "Nutritional Guidelines",
    "Pediatric Growth and Development",
    "Postpartum Care",
    "Pregnancy Nutrition",
    "Prenatal Care",
    "Preventive Care",
    "Reproductive Health",
    "Risk Factor Identification",
    "Self-Breast Examination",
    "Sexual Health",
    "Smoking Cessation",
    "Stress Management",
    "Testicular Self-Examination",
    "Well-Baby Visits",
    "Wellness Exams"
  ],

  "Lab Values & Diagnostics": [
    "ABG Interpretation",
    "Albumin",
    "Alkaline Phosphatase (ALP)",
    "Aspartate Aminotransferase (AST)",
    "Bilirubin",
    "Blood Culture",
    "Blood Glucose",
    "Blood Urea Nitrogen (BUN)",
    "Brain Natriuretic Peptide (BNP)",
    "Calcium",
    "Chloride",
    "Cholesterol",
    "Coagulation Studies (PT/INR/PTT)",
    "Complete Blood Count (CBC)",
    "Computed Tomography (CT)",
    "Creatine Kinase (CK)",
    "Creatinine",
    "Culture and Sensitivity",
    "D-Dimer",
    "Electrocardiogram (ECG)",
    "Electrolyte Panel",
    "Glycosylated Hemoglobin (HbA1c)",
    "Human Chorionic Gonadotropin (hCG)",
    "Lactate",
    "Lipase",
    "Lipid Panel",
    "Liver Function Tests (LFTs)",
    "Lumbar Puncture",
    "Magnetic Resonance Imaging (MRI)",
    "Mean Corpuscular Volume (MCV)",
    "Metabolic Panel",
    "Oxygen Saturation (SpO2)",
    "Potassium",
    "Prostate-Specific Antigen (PSA)",
    "Renal Function Panel",
    "Sodium",
    "Thyroid Function Tests (TSH, T3, T4)",
    "Toxicology Screen",
    "Troponin",
    "Tumor Markers",
    "Ultrasound",
    "Urinalysis",
    "Urine Culture",
    "White Blood Cell Count",
    "X-Ray Interpretation"
  ],

  "Leadership & Management": [
    "Change Management",
    "Conflict Resolution",
    "Delegation",
    "Ethical Decision Making",
    "Evidence-Based Practice",
    "Informed Consent",
    "Interdisciplinary Collaboration",
    "Legal Responsibilities",
    "Malpractice and Liability",
    "Management of Care",
    "Nurse Staffing",
    "Patient Advocacy",
    "Patient Rights",
    "Performance Improvement",
    "Quality Improvement",
    "Resource Management",
    "Risk Management",
    "Root Cause Analysis",
    "Scope of Practice",
    "Staff Development",
    "Standards of Practice",
    "Supervision",
    "Team Building",
    "Time Management",
    "Tort Law"
  ],

  "Maternal & Newborn Nursing": [
    "Antepartum Assessment",
    "Antepartum Bleeding",
    "Breastfeeding",
    "Cesarean Section (C-Section)",
    "Ectopic Pregnancy",
    "Electronic Fetal Monitoring",
    "Gestational Diabetes",
    "Gestational Hypertension",
    "Group B Streptococcus",
    "Hyperemesis Gravidarum",
    "Induction of Labor",
    "Intrapartum Care",
    "Intrapartum Complications",
    "Lochia Assessment",
    "Neonatal Resuscitation (NRP)",
    "Newborn Assessment (APGAR)",
    "Newborn Care",
    "Newborn Jaundice",
    "Non-Stress Test (NST)",
    "Obstetric Pain Management",
    "Placenta Previa",
    "Placental Abruption",
    "Postpartum Assessment",
    "Postpartum Complications",
    "Postpartum Depression",
    "Postpartum Hemorrhage",
    "Preeclampsia",
    "Premature Rupture of Membranes (PROM)",
    "Prenatal Care",
    "Preterm Labor",
    "Rh Incompatibility",
    "Rho(D) Immune Globulin",
    "Spontaneous Abortion (Miscarriage)",
    "TORCH Infections",
    "VBAC (Vaginal Birth After Cesarean)"
  ],

  "Mental Health": [
    "Alcohol Withdrawal",
    "Alzheimer's Disease",
    "Anxiety Disorders",
    "Attention Deficit Hyperactivity Disorder (ADHD)",
    "Autism Spectrum Disorder",
    "Bipolar Disorder",
    "Borderline Personality Disorder",
    "Child Abuse",
    "Cognitive Behavioral Therapy",
    "Crisis Intervention",
    "Defense Mechanisms",
    "Delirium",
    "Dementia",
    "Depression",
    "Domestic Violence",
    "Eating Disorders",
    "Elder Abuse",
    "Elevated Suicide Risk",
    "Grief and Loss",
    "Legal Issues in Mental Health",
    "Lithium Therapy",
    "Major Depressive Disorder",
    "Mania",
    "Mental Health Assessment",
    "Neuroleptic Malignant Syndrome",
    "Obsessive-Compulsive Disorder (OCD)",
    "Panic Disorder",
    "Personality Disorders",
    "Pharmacotherapy",
    "Post-Traumatic Stress Disorder (PTSD)",
    "Psychiatric Emergencies",
    "Psychiatric Medications",
    "Psychosis",
    "Schizophrenia",
    "Selective Serotonin Reuptake Inhibitors (SSRIs)",
    "Self-Harm",
    "Serotonin Syndrome",
    "Sexual Abuse",
    "Substance Abuse",
    "Suicide Assessment",
    "Suicide Prevention",
    "Therapeutic Communication",
    "Therapeutic Environment",
    "Tricyclic Antidepressants (TCAs)",
    "Violence Risk Assessment"
  ],

  "NGN Case Studies": [
    "Bow-Tie Questions",
    "Cloze (Drop-Down) Items",
    "Clustered Items",
    "Comprehensive Case Studies",
    "Drag and Drop Questions",
    "Enhanced Multiple Choice",
    "Extended Multiple Response",
    "Fill-in-the-Blank Questions",
    "Highlight Text Questions",
    "Hotspot Questions",
    "Matching Questions",
    "Multiple Response (SATA) Questions",
    "NGN Question Types",
    "NGN Scoring Methods",
    "Next Generation NCLEX Format",
    "Ordered Response Questions",
    "Partial Credit Scoring",
    "Trend Questions"
  ],

  "Pediatrics": [
    "ADHD Management",
    "Autism Spectrum Disorder",
    "Child Abuse and Neglect",
    "Child Development (Preschool)",
    "Child Development (Toddler)",
    "Congenital Heart Defects",
    "Croup (Laryngotracheobronchitis)",
    "Cystic Fibrosis",
    "Down Syndrome",
    "Failure to Thrive",
    "Hydrocephalus",
    "Immunization Schedule",
    "Intussusception",
    "Iron-Deficiency Anemia",
    "Kawasaki Disease",
    "Lead Poisoning",
    "Meningitis (Pediatric)",
    "Neonatal Care",
    "Neonatal Jaundice",
    "Nursemaid's Elbow",
    "Oral Rehydration Therapy",
    "Otitis Media",
    "Pain Assessment in Children",
    "Pediatric Asthma",
    "Pediatric Cancers (Leukemia)",
    "Pediatric Dehydration",
    "Pediatric Diabetes",
    "Pediatric Fractures",
    "Pediatric Seizures",
    "Phenylketonuria (PKU)",
    "Pyloric Stenosis",
    "Respiratory Syncytial Virus (RSV)",
    "Sickle Cell Disease (Pediatric)",
    "Sudden Infant Death Syndrome (SIDS)",
    "Wilms Tumor"
  ],

  "Pharmacology": [
    "ACE Inhibitors",
    "Acetaminophen",
    "Albuterol",
    "Aminoglycosides",
    "Analgesics",
    "Angiotensin II Receptor Blockers (ARBs)",
    "Antacids",
    "Antiarrhythmics",
    "Antibiotics",
    "Anticoagulants",
    "Anticonvulsants",
    "Antidepressants (SSRIs, SNRIs, TCAs)",
    "Antidiabetic Agents",
    "Antiemetics",
    "Antihypertensives",
    "Anti-Inflammatory Agents",
    "Antilipemics (Statins)",
    "Antineoplastics",
    "Antipsychotics",
    "Beta Blockers",
    "Benzodiazepines",
    "Bronchodilators",
    "Calcium Channel Blockers",
    "Cephalosporins",
    "Corticosteroids",
    "Coumadin (Warfarin)",
    "Diuretics",
    "Drug Interactions",
    "Drug Metabolism",
    "Fibrinolytics (Thrombolytics)",
    "Gastrointestinal Medications",
    "H2 Receptor Blockers",
    "Heparin",
    "Hypoglycemic Agents",
    "Insulin",
    "Lithium",
    "Macrolides",
    "Methotrexate",
    "Monoamine Oxidase Inhibitors (MAOIs)",
    "Morphine and Opioids",
    "Nitrates",
    "NSAIDs",
    "Opioid Antagonists",
    "Oral Contraceptives",
    "Oxytocin",
    "Penicillins",
    "Pharmacokinetics",
    "Platelet Aggregation Inhibitors",
    "Proton Pump Inhibitors (PPIs)",
    "Psychotropic Medications",
    "Sedative-Hypnotics",
    "Sulfonylureas",
    "Thyroid Medications",
    "Vaccines",
    "Vasodilators"
  ]
};

export const categoryList = Object.keys(CATEGORIES);
