export const CATEGORIES = {
  "Adult Health": [
    "Acid\u2013Base Balance",
    "Blood Disorders & Transfusion Reactions",
    "Burns",
    "Cardiovascular",
    "Chronic Illness",
    "Diagnostic Tests & Procedures",
    "Emergency Conditions (Adult)",
    "Endocrine",
    "Eye Disorders",
    "Fluid & Electrolytes",
    "Gastrointestinal",
    "Hepatic & Biliary",
    "Hematology",
    "Immune Disorders",
    "Infectious Diseases",
    "Integumentary",
    "Mobility & Immobility Complications",
    "Musculoskeletal",
    "Neurological",
    "Nutrition in Adult Health",
    "Oncology",
    "Organ Transplant",
    "Pain Management",
    "Palliative Care",
    "Perioperative / Surgical Care",
    "Postoperative Care",
    "Preoperative Care",
    "Rehabilitation",
    "Renal & Urinary",
    "Reproductive",
    "Respiratory",
    "Sepsis",
    "Shock",
    "Sleep Disorders"
  ],

  "Critical Care": [
    "ABG Interpretation",
    "Acid\u2013Base Disorders",
    "Airway Management",
    "Cardiac ICU",
    "Electrolyte Emergencies",
    "Hemodynamic Monitoring",
    "ICU Medications",
    "ICU Monitoring & Equipment",
    "Lines & Tubes",
    "Massive Transfusion",
    "Mechanical Ventilation",
    "Multi-Organ Failure",
    "Neurological ICU",
    "Nutrition in Critical Care (Enteral/TPN ICU)",
    "Renal ICU",
    "Respiratory Failure / ARDS",
    "Resuscitation / Code Blue",
    "Sedation & Paralytics",
    "Sepsis & Septic Shock",
    "Shock States",
    "Temperature Management",
    "Trauma & Emergency Care",
    "Withdrawal of Care / End-of-Life ICU"
  ],

  "Dosage Calculations": [
    "Basic Dosage Calculations",
    "Body Surface Area (BSA) Calculations",
    "Concentration Calculations",
    "Critical Care Drip Calculations",
    "Dimensional Analysis Calculations",
    "Dosage by Age Calculations",
    "Drop Factor Calculations",
    "Formula Method Calculations",
    "Heparin Dose Calculations",
    "Insulin Dose Calculations",
    "Intake & Output Calculations",
    "IV Drip Rate Calculations",
    "IV Flow Rate Calculations",
    "IV Infusion Time Calculations",
    "Liquid Medication Calculations",
    "Medication Reconstitution",
    "Parenteral Nutrition Calculations",
    "Pediatric Dosage Calculations",
    "Percentage Solution Calculations",
    "Ratio & Proportion Calculations",
    "Safe Dose Range Calculations",
    "Tablet / Capsule Calculations",
    "Titration Calculations",
    "Unit Conversions",
    "Weight-Based Dosing"
  ],

  "EKG/Cardiac Monitoring": [
    "ACLS Rhythms",
    "Atrial Fibrillation",
    "Atrial Flutter",
    "Asystole",
    "Artifact Recognition",
    "Axis Deviation",
    "Cardioversion",
    "Cardiac Resynchronization Therapy",
    "Continuous Cardiac Monitoring",
    "Defibrillation",
    "ECG Basics",
    "ECG Interpretation",
    "ECG Intervals",
    "First-Degree AV Block",
    "Heart Rate Calculation",
    "Hypercalcemia ECG Changes",
    "Hyperkalemia ECG Changes",
    "Hypocalcemia ECG Changes",
    "Hypokalemia ECG Changes",
    "Idioventricular Rhythm",
    "Implantable Cardioverter Defibrillator",
    "Lethal Rhythms",
    "Myocardial Infarction",
    "Myocardial Injury",
    "Myocardial Ischemia",
    "Pacemaker Malfunction",
    "Pacemaker Rhythms",
    "Permanent Pacemaker",
    "Premature Atrial Contractions",
    "Premature Ventricular Contractions",
    "Pulseless Electrical Activity",
    "Second-Degree AV Block Type I",
    "Second-Degree AV Block Type II",
    "Shockable vs Non-Shockable Rhythms",
    "Sinus Bradycardia",
    "Sinus Rhythm",
    "Sinus Tachycardia",
    "ST Depression",
    "ST Elevation",
    "Supraventricular Tachycardia",
    "T Wave Changes",
    "Telemetry Monitoring",
    "Temporary Pacing",
    "Third-Degree AV Block",
    "Ventricular Fibrillation",
    "Ventricular Tachycardia"
  ],

  "Emergency Nursing": [
    "Airway Emergencies",
    "Anaphylaxis",
    "Bleeding / Hemorrhage",
    "Burns Emergency",
    "Cardiac Emergencies",
    "Cardioversion",
    "Chest tube",
    "Defibrillation",
    "Disaster Nursing",
    "Drowning",
    "Emergency Procedures",
    "Environmental Emergencies",
    "Head Injury / Spinal Injury",
    "Heat stroke",
    "Hypothermia",
    "Insect bites",
    "Intubation",
    "Mass Casualty Incidents",
    "Myocardial Infarction Emergency",
    "Obstetric Emergencies",
    "Overdose",
    "Pediatric Emergencies",
    "Poisoning",
    "Primary Survey (ABCDE)",
    "Rapid Response / Code Blue",
    "Respiratory Emergencies",
    "Seizures / Status Epilepticus",
    "Shock Emergency",
    "Snake bites",
    "Stroke Emergency",
    "Trauma",
    "Triage"
  ],

  "Fundamentals": [
    "Admission, Transfer & Discharge",
    "Assistive Devices",
    "Basic Care & Comfort",
    "Blood Transfusion",
    "Communication & Therapeutic Communication",
    "Cultural Considerations",
    "Delegation",
    "Documentation",
    "Elimination",
    "End-of-Life Care",
    "Enteral Feeding",
    "Ethical Issues",
    "Foley Catheter Care",
    "Hygiene",
    "Infection Control",
    "Intraoperative Care",
    "IV Therapy",
    "Isolation Precautions",
    "Legal Issues",
    "Medication Administration",
    "Mobility & Positioning",
    "Nutrition",
    "Ostomy Care",
    "Oxygen Therapy",
    "Pain Management",
    "Palliative Care Basics",
    "Parenteral Nutrition (TPN)",
    "Patient Education",
    "Perioperative Care",
    "Postoperative Care",
    "Preoperative Care",
    "Prioritization",
    "Restraints",
    "Safety & Fall Prevention",
    "Specimen Collection",
    "Sterile Technique",
    "Vital Signs",
    "Wound Care"
  ],

  "Health Promotion & Maintenance": [
    "Aging Process",
    "Alcohol & Substance Use Prevention",
    "Chronic Disease Prevention",
    "Community Health Promotion",
    "Developmental Milestones",
    "Environmental Health",
    "Exercise & Physical Activity",
    "Family Planning & Contraception",
    "Follow-Up Care & Compliance",
    "Genetic Screening & Counseling",
    "Geriatric Health Promotion",
    "Growth & Development",
    "Health Education Programs",
    "Health Screening",
    "Immunizations",
    "Infection Prevention",
    "Injury Prevention",
    "Lifestyle Modification",
    "Men\u2019s Health Screening",
    "Newborn Care Education",
    "Nutrition & Diet Education",
    "Occupational Health",
    "Patient Education",
    "Physical Assessment Across Lifespan",
    "Postpartum Education",
    "Prenatal Care",
    "Prenatal Education",
    "Preventive Care",
    "Risk Factor Reduction",
    "Safety Education",
    "Self-Examination Teaching",
    "Sexual Health Education",
    "Sleep Hygiene",
    "Smoking Cessation",
    "Stress Management",
    "Weight Management",
    "Women\u2019s Health Screening"
  ],

  "Lab Values & Diagnostics": [
    "ABG Analysis",
    "Allergy Testing",
    "Amniocentesis",
    "Blood Glucose Tests",
    "Bone Marrow Biopsy",
    "Bronchoscopy",
    "Cardiac Catheterization",
    "Cardiac Diagnostics",
    "Cardiac Enzymes",
    "Coagulation Studies",
    "Colonoscopy",
    "CSF Analysis",
    "CT Scan",
    "Diagnostic Imaging",
    "Drug Levels / Therapeutic Drug Monitoring",
    "ECG",
    "Echocardiogram",
    "EEG",
    "EMG",
    "Electrolyte Labs",
    "Endocrine Labs",
    "Endoscopy",
    "Fetal Diagnostic Tests",
    "GI Diagnostic Tests",
    "Glucose Tolerance Test",
    "Hearing Tests",
    "Hematology Labs",
    "ICP Monitoring",
    "Infection & Culture Tests",
    "Lipid Profile",
    "Liver Function Tests",
    "Lumbar Puncture",
    "MRI",
    "Neurological Diagnostic Tests",
    "Nuclear Medicine Tests",
    "Paracentesis",
    "Postoperative Monitoring Tests",
    "Preoperative Diagnostic Tests",
    "Pregnancy Tests",
    "Pulmonary Function Tests",
    "Renal Diagnostic Tests",
    "Renal Function Tests",
    "Sleep Studies",
    "Specimen Collection & Handling",
    "Sputum Tests",
    "Stress Test",
    "Stool Tests",
    "Thoracentesis",
    "Tumor Markers",
    "Ultrasound",
    "Urinalysis",
    "Vision Tests",
    "X-Ray"
  ],

  "Leadership & Management": [
    "Advance Directives",
    "Advocacy",
    "Assignment",
    "Budgeting & Finance Basics",
    "Case Management",
    "Chain of Command",
    "Change Management",
    "Communication in Management",
    "Conflict Resolution",
    "Delegation",
    "Delegation to LPN",
    "Delegation to UAP",
    "Disaster Management",
    "Documentation & Legal Responsibility",
    "Ethical Dilemmas",
    "Ethical Principles (Autonomy, Beneficence, Justice, etc.)",
    "Evaluation & Performance Appraisal",
    "Informed Consent",
    "Incident Reports",
    "Leadership Styles",
    "Legal Issues in Nursing",
    "Management Principles",
    "Patient Safety",
    "Performance Improvement",
    "Policy & Procedures",
    "Prioritization",
    "Professional Accountability",
    "Quality Improvement",
    "Resource Management",
    "Risk Management",
    "Scope of Practice",
    "Staffing & Scheduling",
    "Supervision",
    "Teamwork & Collaboration",
    "Time Management",
    "Triage (Management Role)",
    "Utilization Review",
    "Workplace Violence & Safety"
  ],

  "Maternal & Newborn Health": [
    "Fetal Monitoring",
    "High-Risk Pregnancy",
    "Intrapartum Complications",
    "Labor & Delivery",
    "Medications in Obstetrics",
    "Newborn Assessment",
    "Newborn Care",
    "Newborn Complications",
    "Obstetric Emergencies",
    "Obstetric Procedures",
    "Pain Management in Labor",
    "Patient Education (Pregnancy / Postpartum / Newborn)",
    "Postpartum Care",
    "Postpartum Complications",
    "Prenatal Assessment",
    "Prenatal Care",
    "Prenatal Labs & Diagnostics",
    "Pregnancy Complications",
    "Pregnancy Discomforts",
    "Stages of Labor"
  ],

  "Mental Health": [
    "Abuse & Neglect",
    "ADHD",
    "Anger Management",
    "Anxiety Disorders",
    "Antidepressants",
    "Antipsychotics",
    "Anxiolytics",
    "Autism Spectrum Disorder",
    "Behavioral Therapy",
    "Bipolar Disorder",
    "Cognitive Disorders",
    "Community Mental Health",
    "Conduct & Oppositional Disorders",
    "Coping & Defense Mechanisms",
    "Crisis Intervention",
    "Cultural Considerations in Mental Health",
    "Delirium",
    "Dementia / Alzheimer\u2019s",
    "Depression",
    "Developmental Disorders",
    "Dissociative Disorders",
    "Eating Disorders",
    "Electroconvulsive Therapy (ECT)",
    "Family Therapy",
    "Group Therapy",
    "Grief & Loss",
    "Legal & Ethical Issues in Psychiatry",
    "Mental Health Assessment",
    "Mood Stabilizers",
    "Obsessive\u2013Compulsive Disorder",
    "Patient Rights",
    "Personality Disorders",
    "Psychiatric Emergencies",
    "Psychopharmacology",
    "Restraints & Seclusion",
    "Schizophrenia & Psychotic Disorders",
    "Sedatives & Hypnotics",
    "Sexual Disorders / Gender Issues",
    "Sleep Disorders",
    "Somatic Symptom Disorders",
    "Stress Management",
    "Substance Use & Addiction",
    "Suicide & Self-Harm",
    "Therapeutic Communication",
    "Trauma & Stress Disorders (PTSD)"
  ],

  "Pediatrics": [
    "Chronic Illness in Children",
    "Congenital Disorders",
    "Developmental Milestones",
    "Family-Centered Care",
    "Growth & Development",
    "Immunizations",
    "Pediatric Abuse & Neglect",
    "Pediatric Assessment",
    "Pediatric Cardiac",
    "Pediatric Emergencies",
    "Pediatric Endocrine",
    "Pediatric Fluid & Electrolytes",
    "Pediatric Gastrointestinal",
    "Pediatric Hematology",
    "Pediatric Infectious Diseases",
    "Pediatric Medication Administration",
    "Pediatric Neurological",
    "Pediatric Nutrition",
    "Pediatric Oncology",
    "Pediatric Pain Management",
    "Pediatric Procedures & Postoperative Care",
    "Pediatric Renal & Urinary",
    "Pediatric Respiratory",
    "Pediatric Safety & Injury Prevention",
    "Pediatric Vital Signs"
  ],

  "Pharmacology": [
    "Anti-Inflammatory Drugs",
    "Antibiotics",
    "Anticoagulants",
    "Antidepressants",
    "Antidotes",
    "Antifungals",
    "Antiplatelets",
    "Antiparasitic Drugs",
    "Antipsychotics",
    "Antiseizure Drugs",
    "Antituberculosis Drugs",
    "Antivirals",
    "Cardiovascular Drugs",
    "Drug Toxicity",
    "Emergency Drugs",
    "Electrolyte Replacement Medications",
    "Endocrine Drugs",
    "Gastrointestinal Drugs",
    "Hematologic Drugs",
    "Immunizations / Vaccines",
    "Immunosuppressants",
    "IV Therapy & Parenteral Medications",
    "Medication Administration & Safety",
    "Medication Calculations",
    "Mood Stabilizers",
    "Neurological Drugs",
    "Obstetric & Gynecologic Drugs",
    "Oncology Drugs (Chemotherapy)",
    "Pain Medications (Analgesics)",
    "Pediatric Drugs",
    "Psychiatric Drugs",
    "Respiratory Drugs",
    "Sedatives & Hypnotics",
    "Thrombolytics"
  ]
};

export const categoryList = Object.keys(CATEGORIES);
